// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5EjUaALcbAMZQ-bZlTry41BHmrC9iIQ',
    appId: '1:1075335928155:web:d2439ff730f1d5f250627e',
    messagingSenderId: '1075335928155',
    projectId: 'food-and-dining-76331',
    authDomain: 'food-and-dining-76331.firebaseapp.com',
    storageBucket: 'food-and-dining-76331.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrufKnaTZNtNgoFuXrgKGCgCSKxayyGOw',
    appId: '1:1075335928155:android:21175aed20746ca850627e',
    messagingSenderId: '1075335928155',
    projectId: 'food-and-dining-76331',
    storageBucket: 'food-and-dining-76331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8l0C3G-Jab67fasKFWA_vaHJmOPR2rY',
    appId: '1:1075335928155:ios:2dbd68d90a270f1a50627e',
    messagingSenderId: '1075335928155',
    projectId: 'food-and-dining-76331',
    storageBucket: 'food-and-dining-76331.appspot.com',
    iosClientId: '1075335928155-4694fm5c19g1urg8g42t01qs5eck4b8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX8l0C3G-Jab67fasKFWA_vaHJmOPR2rY',
    appId: '1:1075335928155:ios:2dbd68d90a270f1a50627e',
    messagingSenderId: '1075335928155',
    projectId: 'food-and-dining-76331',
    storageBucket: 'food-and-dining-76331.appspot.com',
    iosClientId: '1075335928155-4694fm5c19g1urg8g42t01qs5eck4b8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminAplication',
  );
}
